### ISSUE TITLE
geom_half_violin() error 

### ISSUE THREAD

**Issue by cogneuro** [erocoar/gghalves#17]
Hi Frederik, 

After updating "gghalves" into 0.1.2 today, I have trouble reproducing figures.

```
library(gghalves)

ggplot(data = ToothGrowth, aes(x = 1, y = len)) +
	geom_half_point(aes(y = len), side = "l", 
		color = "grey50", fill = "grey50", alpha = .5) +
	geom_half_violin(aes(y = len), side = "r", 
		color = "grey70", fill = "grey70") +
	coord_flip() +
	theme_bw() +
	theme(panel.grid.major = element_blank(),
		panel.grid.minor = element_blank(),
		axis.title.y = element_blank(),
		axis.ticks.y = element_blank(),
		axis.text.y = element_blank(),
		aspect.ratio = .3)
```

The code above worked fine to make the figure below.

![raincloud](https://user-images.githubusercontent.com/17180059/170730653-fb5f61f0-2652-4bd4-bfcf-3c49bc1f8de7.png)

After updating, however, I have this error.
```
Error in rep(side, data$group[1]) : invalid 'times' argument
```

I realized that the error was generated by "geom_half_violin()."  
It seems that "geom_half_point()" was not updated, so it works fine.  
Could you check what is wrong? 

Thank you for your work.

Do-Joon

**Comment by erocoar** [comment]
Hi, thanks for pointing this out! I did not notice this earlier, but with https://github.com/erocoar/gghalves/pull/16 `geom_half_violin` stopped working for panel plots. I've fixed it now and will add your example to the development tests. 😄 Will be on CRAN shortly

**Comment by cogneuro** [comment]
Awesome! Thank you so much for such a quick fix.
