### ISSUE TITLE
Is it possible to draw all the points together but color them separately?

### ISSUE THREAD

**Issue by tungmilan** [erocoar/gghalves#4]
Happy Friday,

A follow-up from [this issue](https://github.com/erocoar/ggpol/issues/4). Can we somehow get the combination of  the 1st & 2nd plots?

Plot all the points together 

``` r

library(ggplot2)
library(ggbeeswarm)
library(ggpol)
library(gghalves)

h1 <- ggplot(iris, aes(y = Petal.Width)) +
  geom_boxjitter(
    errorbar.draw = TRUE,
    jitter.position = ggbeeswarm:::PositionQuasirandom,
    jitter.params = formals(position_quasirandom)) +
  theme_classic()
h1
```

![](https://i.imgur.com/zwSPg0v.png)

With `geom_half_point()`, points are now colored differently but they are also not together anymore 

``` r


h2 <- ggplot(iris, aes(y = Sepal.Width)) +
  geom_half_boxplot() +
  geom_half_point(aes(x = 0.5, color = Species),
                  transformation = ggbeeswarm:::PositionQuasirandom,
                  transformation_params = formals(ggbeeswarm::position_quasirandom)) +
  theme_classic()
h2
```

![](https://i.imgur.com/98hEjoh.png)

``` r


h3 <- ggplot(iris, aes(y = Sepal.Width)) +
  geom_half_boxplot() +
  geom_half_point(aes(color = Species),
                  transformation = ggbeeswarm:::PositionQuasirandom,
                  transformation_params = formals(ggbeeswarm::position_quasirandom)) +
  theme_classic()
h3
```

![](https://i.imgur.com/3BbXaiK.png)

<sup>Created on 2019-10-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by erocoar** [comment]
I have now implemented this by adding a `geom_half_point_panel`, where instead of per grouping, the entire panel is computed at once, meaning that you can use all points for computing the position (quasirandom, jitter, beeswarm) but then differentiate them via color, shape etc. - see the example:

``` r
library(ggplot2)
library(gghalves)
ggplot(iris, aes(y = Sepal.Width)) +
  geom_half_boxplot() +
  geom_half_point_panel(aes(x = 0.5, color = Species),
                  transformation = ggbeeswarm:::PositionQuasirandom,
                  transformation_params = formals(ggbeeswarm::position_quasirandom)) +
  theme_classic()
```

![](https://i.imgur.com/a8znrpb.png)

<sup>Created on 2020-02-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by tungmilan** [comment]
Thank you @erocoar !
