### ISSUE TITLE
y-axis automatically (and incorrectly) rescaling

### ISSUE THREAD

**Issue by andrewheiss** [erocoar/gghalves#6]
One more weird bug I've come across! When dealing with lots of small numbers between 0 and 1, the y-axis gets rescaled to match the number of factor levels. If there are 3 categories, the y-axis goes from 0 to 3, etc.

Right now it's fixable by manually setting the axis limits with `coord_cartesian(ylim = c(0, 1))` or with `scale_y_continuous()`, but it'd be nice to not have to manually adjust the scales every time. 

``` r
library(tidyverse)
library(gghalves)

# The y axis automatically goes from 0 to 6, which matches the 7 categories
df_example_7 <- tibble(categories = as.factor(rep(0:6, 1000)),
                       values = runif(7000))

ggplot(df_example_7, aes(x = categories, y = values)) +
  geom_half_boxplot(side = "r") + 
  geom_half_point(side = "l", size = 0.1, alpha = 0.1)
```

![](https://i.imgur.com/qDSRPpj.png)

``` r

# The y-axis automatically goes from 0 to 3, which matches the 3 categories
df_example_3 <- tibble(categories = as.factor(rep(0:2, 1000)),
                       values = runif(3000))

ggplot(df_example_3, aes(x = categories, y = values)) +
  geom_half_boxplot(side = "r") + 
  geom_half_point(side = "l", size = 0.1, alpha = 0.1)
```

![](https://i.imgur.com/GO0m1HU.png)

<sup>Created on 2020-02-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by erocoar** [comment]
Thanks for reporting this! I have fixed it in e5a8ea119d74774e545c8bb3469d6b05ad1040d0 -- if it works in all use cases that I can see I will push it to CRAN with the other fix in the next week
